services:
  - type: web
    name: front-olympique
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    rootDir: .
